# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaur',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
